// RobotBuilder Version: 1.0
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2811.AerialAssist;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.buttons.*;
import org.usfirst.frc2811.AerialAssist.commands.AimToggle;
import org.usfirst.frc2811.AerialAssist.commands.ArmDown;
import org.usfirst.frc2811.AerialAssist.commands.ArmUp;
import org.usfirst.frc2811.AerialAssist.commands.PuntSystem;
import org.usfirst.frc2811.AerialAssist.commands.ReLoad;
import org.usfirst.frc2811.AerialAssist.commands.ShiftGear;
import org.usfirst.frc2811.AerialAssist.commands.ShootingSequence;
import org.usfirst.frc2811.AerialAssist.commands.TrussGroup;
import org.usfirst.frc2811.AerialAssist.commands.UnLoad;

/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
           
    public JoystickButton truss;
    public JoystickButton shift;
    public JoystickButton spitBall; 
    public JoystickButton suckBall;
    public JoystickButton punt;
    public JoystickButton shoot;
    public JoystickButton aimDown;
    public JoystickButton aimUp;
    //public JoystickButton b9;//not yet used
    public JoystickButton manual;
    //public JoystickButton b11;//not yet used
    
    public static int FORE_BACK_STICK;//joystick for controlling robot in freedom
    public static final int FORE_BACK_STICK_CONTROLLER = 3;
    public static final int FORE_BACK_STICK_JOYSTICK = 1;
    public static int LEFT_RIGHT_STICK;
    public static boolean FORE_BACK_DIRECTION;//reverses direction of the stick
    public static boolean LEFT_RIGHT_DIRECTION;
   
    public OI() {
        
       joystick1 = new Joystick(1);
              
       truss = new JoystickButton(joystick1, 1);
       shift = new JoystickButton(joystick1, 2);
       spitBall = new JoystickButton(joystick1, 3);
       suckBall = new JoystickButton(joystick1, 4);
       punt = new JoystickButton(joystick1, 5);
       shoot = new JoystickButton(joystick1, 6);
       aimDown = new JoystickButton(joystick1, 7);
       aimUp = new JoystickButton(joystick1, 8);
       //b9 = new JoystickButton(joystick1, 9); //not assigned
       manual = new JoystickButton(joystick1, 10); //enable/disable auto-aiming
       //b11 = new JoystickButton(joystick1, 11); //not assigned
              
       truss.whenReleased(new TrussGroup());
       shift.whenReleased(new ShiftGear());
       spitBall.whenReleased(new UnLoad());
       suckBall.whenReleased(new ReLoad());
       punt.whenReleased(new PuntSystem());
       shoot.whenReleased(new ShootingSequence()); 
       aimDown.whileHeld(new ArmDown()); 
       aimUp.whileHeld(new ArmUp());
       //b9.whenReleased(null);    //not assigned
       manual.whenReleased(new AimToggle());//TODO Add Toggle
       //b11.whenReleased(null; //not assigned       
    }
        
    public Joystick getJoystick1() {
        return joystick1;
    }
    
    public static Joystick joystick1 = new Joystick(1);
      
    public static boolean stickEngaged;
    public static boolean armed;
    public static boolean shootMotors;
    public static boolean punchActive;
    public static boolean autoAimEnable;
        
}

