// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2811.AerialAssist;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.buttons.*;
import org.usfirst.frc2811.AerialAssist.commands.ArmDown;
import org.usfirst.frc2811.AerialAssist.commands.ArmUp;
import org.usfirst.frc2811.AerialAssist.commands.PuntSystem;
import org.usfirst.frc2811.AerialAssist.commands.ReLoad;
import org.usfirst.frc2811.AerialAssist.commands.ShiftGear;
import org.usfirst.frc2811.AerialAssist.commands.ShootingSequence;
import org.usfirst.frc2811.AerialAssist.commands.TrussGroup;
import org.usfirst.frc2811.AerialAssist.commands.UnLoad;

/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {

    public JoystickButton truss1;
    public JoystickButton shift2;
    public JoystickButton spitBall3; 
    public JoystickButton suckBall4;
    public JoystickButton punt5;
    public JoystickButton shoot6;
    public JoystickButton aimDown7;
    public JoystickButton aimUp8;
    public JoystickButton b9;
    public JoystickButton manual10;
    public JoystickButton b11;
    
    public static int FORE_BACK_STICK;//joystick for controlling robot in freedom
    public static final int FORE_BACK_STICK_CONTROLLER = 3;
    public static final int FORE_BACK_STICK_JOYSTICK = 1;
    public static int LEFT_RIGHT_STICK;
    public static boolean FORE_BACK_DIRECTION;//reverses direction of the stick
    public static boolean LEFT_RIGHT_DIRECTION;
   
    public OI() {
        
       joystick1 = new Joystick(1);
        
       truss1 = new JoystickButton(joystick1, 1);
       shift2 = new JoystickButton(joystick1, 2);
       spitBall3 = new JoystickButton(joystick1, 3);
       suckBall4 = new JoystickButton(joystick1, 3);
       punt5 = new JoystickButton(joystick1, 5);
       shoot6 = new JoystickButton(joystick1, 6);
       aimDown7 = new JoystickButton(joystick1, 7);
       aimUp8 = new JoystickButton(joystick1, 8);
       b9 = new JoystickButton(joystick1, 9);
       manual10 = new JoystickButton(joystick1, 10);
       
       truss1.whenReleased(new TrussGroup());
       shift2.whenReleased(new ShiftGear());
       spitBall3.whenReleased(new UnLoad());
       suckBall4.whenReleased(new ReLoad());
       punt5.whenReleased(new PuntSystem());
       shoot6.whenReleased(new ShootingSequence());
       aimDown7.whenReleased(new ArmDown());
       aimUp8.whenReleased(new ArmUp());
       b9.whenReleased(null);
       manual10.whenReleased(null);
       b11.whenReleased(null);
       
    }
        
    public Joystick getJoystick1() {
        return joystick1;
    }
    
    public static Joystick joystick1 = new Joystick(1);
      
    public static boolean stickEngaged;
    public static boolean armed;
    public static boolean shootMotors;
    public static boolean punchActive;
    public static boolean autoAimEnable;
        
}

