// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2811.AerialAssist.subsystems;

import org.usfirst.frc2811.AerialAssist.RobotMap;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Rollers extends Subsystem {
    SpeedController speedController6 = RobotMap.rollersSpeedController;


    public void initDefaultCommand() {
    }
    
    public void Spit(){
        speedController6.set(-.25);
    }
    
    public void Suck(){
        speedController6.set(.25);
    }
    
    public void Off(){
        speedController6.set(0);
    }
    
   
    
}

